{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
{{- if .Values.ingress.tls }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.class }}"
    kubernetes.io/tls-acme: "true"
{{- end }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  rules:
  - host: "{{ .Values.externalUrl.hostname }}"
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 80
        path: /
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - "{{ .Values.externalUrl.hostname }}"
    secretName: {{ template "fullname" . }}-tls
{{- end }}
{{- end }}